spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enable: false
    gateway:
      forwarded:
        enabled: false
      x-forwarded:
        protoEnabled: false
        portEnabled: false
      routes:
        - id: endpoint
          uri: lb://endpoint
          predicates:
#            - Path=/greeting/**
#            - Path=/token/**
            - Path=/**
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}


server:
  port: 8888
